name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file host/Serender.Test.HttpApi.Host/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/deneme

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/deneme

      - name: Run Docker Container Locally
        run: |
          docker run --name some-redis -d -p 127.0.0.1:6379:6379 redis

      - name: Test Container
        run: |
          # Burada konteyneri test etmek için gereken komutları çalıştırabilirsiniz
          # Örneğin, cURL veya bir HTTP istemcisi kullanabilirsiniz

     
