name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mydocker:
        image: docker:20.10-dind
        ports:
          - 8080:80
        options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file host/Serender.Test.HttpApi.Host/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/deneme

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/deneme

      - name: Run Docker Container Locally
        run: docker run -d -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/deneme
        continue-on-error: true
        # Konteyner başlamasını beklemek için bir süre bekleme işlemi eklenebilir.
        # Örnek olarak, sleep 10

      - name: Test Container
        run: |
          # Burada konteyneri test etmek için gereken komutları çalıştırabilirsiniz
          # Örneğin, cURL veya bir HTTP istemcisi kullanabilirsiniz

      - name: Stop Docker Container
        run: docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/deneme)
